### PR TITLE
ttbar-spring16-80X.weights.xml was missing

### PR DESCRIPTION
**Pull request by silviodonato**

### CODE REVIEW

**Comment by jpata** [comment]
While we'll need to add it when we update vhbb, I don't even have this file in my vhbb base currently:

~~~
[jpata@t3ui17 crab_vhbb]$ ls -1 $CMSSW_BASE/src/VHbbAnalysis/Heppy/test/ttbar*
/mnt/t3nfs01/data01/shome/jpata/tth/sw/CMSSW/src/VHbbAnalysis/Heppy/test/ttbar-fall15_TargetGenOverPt_GenPtCut0.weights.xml
/mnt/t3nfs01/data01/shome/jpata/tth/sw/CMSSW/src/VHbbAnalysis/Heppy/test/ttbar-fall15.weights.xml
/mnt/t3nfs01/data01/shome/jpata/tth/sw/CMSSW/src/VHbbAnalysis/Heppy/test/ttbar-spring15.weights.xml
~~~

I believe you're using a newer version of the vhbb code.

**Comment by silviodonato** [comment]
I think so. In general I think we should fix some tag in the VHbb code, just to be sure that we are using the same code!

**Comment by jpata** [comment]
in a sense we have this tag, simply our recipe was not properly referring to it: https://github.com/jpata/cmssw/tree/meanalysis-80x

**Comment by silviodonato** [comment]
So you freeze the VHbb version used for ttH in  https://github.com/jpata/cmssw/tree/meanalysis-80x .
I missed this point. Great, it solves the problem!

**Pull request closed without merging**
